### ISSUE TITLE
HI,I try to train 4 classes about pose estimate,and have some problems.

### ISSUE THREAD

**Issue by moore0312** [mohammedAljadd/yolov7-pose-multiclass#1]
When i try to train 4 classes about my dataset,this problem came out:
autoanchor: Analyzing anchors... anchors/target = 6.66, Best Possible Recall (BPR) = 1.0000
Image sizes 640 train, 640 test
Using 8 dataloader workers
Logging results to runs/train/custom-pose2
Starting training for 5 epochs...

     Epoch   gpu_mem       box       obj       cls       kpt      kptv     total    labels  img_size
       0/4     6.22G   0.08629     0.119   0.02208    0.2182   0.02178    0.4673        16       640: 100%|███| 298/298 [03:10<00:00,  1.56it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0%|                     | 0/100 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 562, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 369, in train
    results, maps, times = test.test(data_dict,
  File "/home/gilbert11/Downloads/yolov7-pose-multiclass/test.py", line 125, in test
    out, train_out = model(img, augment=augment)  # inference and training outputs
  File "/home/gilbert11/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 361, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 395, in forward_once
    x = m(x)  # run
  File "/home/gilbert11/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 283, in forward
    x_kpt[..., 0::3] = (x_kpt[..., ::3] * 2. - 0.5 + kpt_grid_x.repeat(1,1,1,1,17)) * self.stride[i]  # xy
RuntimeError: The size of tensor a (18) must match the size of tensor b (17) at non-singleton dimension 4

can you help me? 
Thanks a lot.

**Comment by dongjiang327** [comment]
Hi,mohammedAljadd.Thank you for sharing.
 
I also encountered the same problem when training multiple classes of data. Does anyone know how to solve this problem? Looking forward to your answer. Thank you in advance.

========================
Transferred 622/908 items from weights/yolov7-w6-person.pt
Scaled weight_decay = 0.0005
Optimizer groups: 155 .bias, 155 conv.weight, 155 other
train: Scanning 'wheelchair/train.cache' images and labels... 50 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████████████████████████████████| 3/3 [00:00<?, ?it/s]
val: Scanning 'wheelchair/val.cache' images and labels... 10 found, 0 missing, 0 empty, 0 corrupted: 100%|██████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Plotting labels...

autoanchor: Analyzing anchors... anchors/target = 7.67, Best Possible Recall (BPR) = 1.0000
Image sizes 960 train, 960 test
Using 8 dataloader workers
Logging results to runs/train/yolov7-w6-pose2
Starting training for 300 epochs...

     Epoch   gpu_mem       box       obj       cls       kpt      kptv     total    labels  img_size
     0/299     19.2G    0.1102     3.032   0.03873       nan   0.03907       nan         6       960: 100%|█████████████████████████████████| 7/7 [00:16<00:00,  2.36s/it]
/opt/conda/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0%|                                                 | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 562, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 369, in train
    results, maps, times = test.test(data_dict,
  File "/nfs/dj/yolov7-pose/test.py", line 125, in test
    out, train_out = model(img, augment=augment)  # inference and training outputs
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs/dj/yolov7-pose/models/yolo.py", line 361, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/nfs/dj/yolov7-pose/models/yolo.py", line 395, in forward_once
    x = m(x)  # run
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs/dj/yolov7-pose/models/yolo.py", line 283, in forward
    x_kpt[..., 0::3] = (x_kpt[..., ::3] * 2. - 0.5 + kpt_grid_x.repeat(1,1,1,1,17)) * self.stride[i]  # xy
RuntimeError: The size of tensor a (19) must match the size of tensor b (17) at non-singleton dimension 4
========================

**Comment by dongjiang327** [comment]
> When i try to train 4 classes about my dataset,this problem came out: autoanchor: Analyzing anchors... anchors/target = 6.66, Best Possible Recall (BPR) = 1.0000 Image sizes 640 train, 640 test Using 8 dataloader workers Logging results to runs/train/custom-pose2 Starting training for 5 epochs...
> 
> ```
>  Epoch   gpu_mem       box       obj       cls       kpt      kptv     total    labels  img_size
>    0/4     6.22G   0.08629     0.119   0.02208    0.2182   0.02178    0.4673        16       640: 100%|███| 298/298 [03:10<00:00,  1.56it/s]
>            Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0%|                     | 0/100 [00:03<?, ?it/s]
> ```
> 
> Traceback (most recent call last): File "train.py", line 562, in train(hyp, opt, device, tb_writer) File "train.py", line 369, in train results, maps, times = test.test(data_dict, File "/home/gilbert11/Downloads/yolov7-pose-multiclass/test.py", line 125, in test out, train_out = model(img, augment=augment) # inference and training outputs File "/home/gilbert11/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 361, in forward return self.forward_once(x, profile) # single-scale inference, train File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 395, in forward_once x = m(x) # run File "/home/gilbert11/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/gilbert11/Downloads/yolov7-pose-multiclass/models/yolo.py", line 283, in forward x_kpt[..., 0::3] = (x_kpt[..., ::3] * 2. - 0.5 + kpt_grid_x.repeat(1,1,1,1,17)) * self.stride[i] # xy RuntimeError: The size of tensor a (18) must match the size of tensor b (17) at non-singleton dimension 4
> 
> can you help me? Thanks a lot.

Hi,
I solved this problem, try changing the code below please:
x_kpt[..., 0::3] = (x_kpt[..., ::3] * 2. - 0.5 + kpt_grid_x.repeat(1,1,1,1,18)) * self.stride[i] # xy

**Comment by mohammedAljadd** [comment]
Hello, i forgot about this repo long time ago, can you tell me if you still looking for a solution?
